### ISSUE TITLE
Client generation fails for a valid Open API specification showing "Couldn't read or parse the definition file" error

### ISSUE THREAD

**Issue by SanduDS** [ballerina-platform/ballerina-openapi#380] opened 2021-07-13 11:50 UTC
**Description:**
Client code generation fails for [this Open API specification](https://github.com/APIs-guru/openapi-directory/blob/main/APIs/soundcloud.com/1.0.0/openapi.yaml). This specification was verified using the swagger editor.
When removing default fields of line 1550(`default: playable,preview`), I got the following errors.

```
[2021-07-13 17:17:23,200] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.generators.client.FunctionSignatureGenerator.getQueryParameters(FunctionSignatureGenerator.java:283)
        at io.ballerina.generators.client.FunctionSignatureGenerator.setFunctionParameters(FunctionSignatureGenerator.java:193)
        at io.ballerina.generators.client.FunctionSignatureGenerator.getFunctionSignatureNode(FunctionSignatureGenerator.java:130)
        at io.ballerina.generators.client.BallerinaClientGenerator.getFunctionDefinitionNode(BallerinaClientGenerator.java:567)
        at io.ballerina.generators.client.BallerinaClientGenerator.createRemoteFunctions(BallerinaClientGenerator.java:516)
        at io.ballerina.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:410)
        at io.ballerina.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:238)
        at io.ballerina.openapi.CodeGenerator.generateClient(CodeGenerator.java:406)
        at io.ballerina.openapi.CodeGenerator.generateBalSource(CodeGenerator.java:225)
        at io.ballerina.openapi.CodeGenerator.generate(CodeGenerator.java:113)
        at io.ballerina.openapi.CodeGenerator.generateClient(CodeGenerator.java:152)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:255)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:205)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:136)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
 ```

**Affected Product Version:**
Tool Ballerina Swan Lake Beta 2
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Generate the client using the above-linked specification.

**Comment by aneeshafedo** [comment] 2021-07-13 14:49
The issue is with the open-api definition file given. Here also we have a query parameter with a schema. Currently ballerina does not support query parameters as records. https://github.com/APIs-guru/openapi-directory/blob/c1e8715fc128f9a79611c8a981023e7cff43a19f/APIs/soundcloud.com/1.0.0/openapi.yaml#L1559.

I went through the api documentation i couldnt find the matching endpoint for this operation there.

Currently we hv merged a fix to return a proper error message in this kind of scenarios. https://github.com/ballerina-platform/ballerina-openapi/pull/374

**Closed** 2021-07-13 15:07 UTC
